# Generated by Django 4.2.1 on 2023-06-03 03:40

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('quantity', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999)])),
                ('quantity_limit', models.PositiveIntegerField(default=0)),
                ('sold', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
