# Generated by Django 4.2.1 on 2023-08-25 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customer_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_stripe_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
