# Generated by Django 4.2.1 on 2023-08-30 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_order_stripe_charge_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
    ]
