# Generated by Django 4.2.1 on 2023-09-15 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_orderitem_item_process_return_initiated'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_amount_returning',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
