# Generated by Django 4.2.1 on 2023-09-15 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_orderitem_item_amount_returning'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='all_items_returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='partial_returned',
            field=models.BooleanField(default=False),
        ),
    ]
