# Generated by Django 4.2.1 on 2023-10-22 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_order_billing_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
    ]
