# Generated by Django 4.2.1 on 2023-11-18 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_address_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='all_order_items_returned',
            field=models.BooleanField(default=False),
        ),
    ]
